# Generated by Django 5.2.5 on 2025-08-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_category_alter_expense_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'CASH'), ('card', 'CARD'), ('upi', 'UPI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('expense', 'EXPENSE'), ('income', 'INCOME')], default='expense', max_length=10),
        ),
    ]
